# TF Basics


In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [3]:
#create two constant variable hello and world
hello=tf.constant("hello ")
world= tf.constant("world")

In [4]:
# to check datatype of hello variable
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
#printing a constant tensor donot give result
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
# to print we have to run it in a session
#with - automatically opens and close the session
with tf.Session() as sess:
    result=sess.run(hello+world)

In [9]:
#b represent that result variable is a bytes literal 
print(result)

b'hello world'


In [10]:
#addition
a=tf.constant(10)
b=tf.constant(20)


In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
a+b


<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [14]:
a+b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [15]:
#add_2.0,3.0... is keeping track of how many times this operation has been executed


In [17]:
with tf.Session() as sess:
    result=sess.run(a+b)
    
result

30

# Numpy Operations


In [18]:
const=tf.constant(10)

In [20]:
#it takes dimentions and a constant value to fill as argument
fill_mat=tf.fill((4,4),10)

In [21]:
#it takes dimention as argument
myzeros=tf.zeros((4,4))

In [22]:
#it takes dimention as argument
myones=tf.ones((4,4))

In [23]:
#creating values from normal distribution
#pass dimention as argument
#can also pass mean and std dev as argument
my_randn=tf.random_normal((4,4),mean=0,stddev=1.0)

In [26]:
#create uniform distribution. 
#pass dimentions, min and max values i.e from where to where
my_randu=tf.random_uniform((4,4), minval=0, maxval=1)

In [27]:
#creating a list for all the operations we have performend
my_opr=[const,fill_mat,myones,myzeros,my_randn,my_randu]

In [31]:
#using interactive session. You can use normal method as well
sess=tf.InteractiveSession()

In [39]:
#you can write op.eval() in place of sess.run(opr) as all the tensors has an evel methodfor opr in my_opr:
for opr in my_opr:
    print(opr.eval())
    #print(sess.run(opr))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.4432316   0.2349761   0.19734049 -0.2042903 ]
 [-1.588218    0.25705543 -0.00611728  0.28964138]
 [-0.97203296 -0.5521368   0.45024756  1.3489184 ]
 [-1.5436957  -0.3574086  -0.9037569  -0.06219577]]


[[0.0945884  0.24542451 0.04163098 0.05114806]
 [0.7692554  0.55788016 0.19109821 0.50062156]
 [0.15000021 0.3894596  0.6848835  0.8642775 ]
 [0.6666546  0.8123722  0.21953917 0.8680545 ]]




In [43]:
#create a list in form of matrix
a=tf.constant([[1,2],
             [3,4]])

In [44]:
#to get the no. or rows and no. of columnsof a tensor
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [45]:
b=tf.constant([[1],[100]])

In [46]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [47]:
#multipying matrixof 2x2 to 2x1 to get 2x1 output
result=tf.matmul(a,b)

In [50]:
#we runned this way because we have interaction sessio on
sess.run(result)

array([[201],
       [403]])

In [51]:
result.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [53]:
#you could use eval in place of get_shape
#evaluate is used to evaluate an operation
result.eval()

array([[201],
       [403]])